<?xml version="1.0" encoding="UTF-8"?>
<!--
*** SPDX-FileCopyrightText: 2023 Linutronix GmbH
*** SPDX-License-Identifier: GPL-2.0-only
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

  <xs:simpleType    name="vendoridType">
    <xs:restriction base="xs:string">
      <xs:length    value="12"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="vendorType">
    <xs:attribute type="xs:string"    name="id"       use="required"/>
    <xs:attribute type="vendoridType" name="vendorid" use="required"/>
    <xs:attribute type="xs:boolean"   name="x64"      use="optional"/>
  </xs:complexType>

  <xs:complexType name="cpuvendorsType">
    <xs:sequence>
      <xs:element name="vendor"       type="vendorType"
		  minOccurs="1"       maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element     name="cpuvendors"   type="cpuvendorsType"/>
</xs:schema>
